import type { Binder, SupersededRecord, DuplicateRecord, CfaRecord, NfrRecord } from '@/lib/types'

const PDF_PATH = '/documents/1TDI-CCH-2024-binder.pdf'

/* Pre-rendered page images for reliable prototype rendering */
const IMG = {
  '1099-div':          '/documents/pages/1099-div-exxonmobil.jpg',
  '1099-div-corrected':'/documents/pages/1099-div-exxonmobil-corrected.jpg',
  '1099-div-draft':    '/documents/pages/1099-div-exxonmobil-draft.jpg',
  'w2':                '/documents/pages/w2-whynot-stop.jpg',
  'w2-corrected':      '/documents/pages/w2-whynot-stop-corrected.jpg',
  '1099-int':          '/documents/pages/1099-int-chase.jpg',
  '1099-int-updated':  '/documents/pages/1099-int-chase-updated.jpg',
  '1099-b':            '/documents/pages/1099-b-schwab.jpg',
  '1099-b-final':      '/documents/pages/1099-b-schwab-final.jpg',
  '1099-b-preliminary':'/documents/pages/1099-b-schwab-preliminary.jpg',
  'k1':                '/documents/pages/k1-chapman-trust.jpg',
  'k1-amended':        '/documents/pages/k1-chapman-trust-amended.jpg',
  '1099-r':            '/documents/pages/1099-r-fidelity.jpg',
  '1099-r-corrected':  '/documents/pages/1099-r-fidelity-corrected.jpg',
  'schedule-c':        '/documents/pages/schedule-c-craft-shop.jpg',
  '1099-misc':         '/documents/pages/1099-misc-richmont.jpg',
}

export const binderA: Binder = {
  id: 'demo-a',
  label: 'Demo Binder',
  taxpayerName: 'Jill Anderson',
  taxYear: 2024,
  totalDocuments: 48,
  summary: [
    { wizardType: 'superseded', totalItems: 14, highConfidence: 5, mediumConfidence: 5, lowConfidence: 4 },
    { wizardType: 'duplicate', totalItems: 6, highConfidence: 3, mediumConfidence: 2, lowConfidence: 1 },
    { wizardType: 'cfa', totalItems: 4, highConfidence: 3, mediumConfidence: 1, lowConfidence: 0 },
    { wizardType: 'nfr', totalItems: 5, highConfidence: 3, mediumConfidence: 1, lowConfidence: 1 },
  ],
}

// The real PDF has 48 pages. The AI found 2 ExxonMobil 1099-DIV documents
// (pages 21 and 32) which are the same form type from the same payer.
// One is the original and one is superseded.
//
// ── 1099-DIV (ExxonMobil / Computershare) ── 1 Original + 1 Superseded
export const supersededA: SupersededRecord[] = [
  {
    engagementPageId: 21,
    isSuperseded: true,
    retainedPageId: 32,
    confidenceLevel: 0.92,
    decisionType: 'Superseded',
    appliedRuleSet: 'SourceDocs',
    decisionRule: 'SUPERSEDED_BY_CORRECTED',
    decisionReason: 'NEWER_VERSION|Page 32 replaces page 21||SAME_RECIPIENT|Documents match the same person||UPDATED_VALUES|Newer document has corrections',
    reviewRequired: false,
    escalationReason: null,
    documentRef: { pdfPath: PDF_PATH, pageNumber: 21, formType: '1099-DIV', formLabel: '1099-DIV (ExxonMobil)', imagePath: IMG['1099-div'] },
    comparedValues: [
      { field: 'Payer Name', valueA: 'EXXON MOBIL CORPORATION', valueB: 'EXXON MOBIL CORPORATION', match: true, category: 'Payer Info', cropA: { x: 0.05, y: 0.12, width: 0.42, height: 0.04 }, cropB: { x: 0.05, y: 0.12, width: 0.42, height: 0.04 } },
      { field: 'Payer (Transfer Agent)', valueA: 'COMPUTERSHARE', valueB: 'COMPUTERSHARE', match: true, category: 'Payer Info', cropA: { x: 0.05, y: 0.17, width: 0.42, height: 0.04 }, cropB: { x: 0.05, y: 0.17, width: 0.42, height: 0.04 } },
      { field: 'Recipient Name', valueA: 'JILL ANDERSON', valueB: 'JILL ANDERSON', match: true, category: 'Recipient Info', cropA: { x: 0.05, y: 0.24, width: 0.42, height: 0.04 }, cropB: { x: 0.05, y: 0.24, width: 0.42, height: 0.04 } },
      { field: 'Recipient SSN', valueA: '***-**-1234', valueB: '***-**-1234', match: true, category: 'Recipient Info', cropA: { x: 0.05, y: 0.29, width: 0.25, height: 0.04 }, cropB: { x: 0.05, y: 0.29, width: 0.25, height: 0.04 } },
      { field: 'Total Ordinary Dividends (Box 1a)', valueA: '$3,285.60', valueB: '$3,412.80', match: false, category: 'Income', cropA: { x: 0.52, y: 0.32, width: 0.44, height: 0.05 }, cropB: { x: 0.52, y: 0.32, width: 0.44, height: 0.05 } },
      { field: 'Qualified Dividends (Box 1b)', valueA: '$2,890.40', valueB: '$3,012.50', match: false, category: 'Income', cropA: { x: 0.52, y: 0.38, width: 0.44, height: 0.05 }, cropB: { x: 0.52, y: 0.38, width: 0.44, height: 0.05 } },
      { field: 'Document Number', valueA: 'D04018', valueB: 'D04018-C', match: false, category: 'Document', cropA: { x: 0.72, y: 0.06, width: 0.24, height: 0.04 }, cropB: { x: 0.72, y: 0.06, width: 0.24, height: 0.04 } },
      { field: 'Corrected', valueA: 'No', valueB: 'Yes', match: false, category: 'Document', cropA: { x: 0.30, y: 0.04, width: 0.14, height: 0.04 }, cropB: { x: 0.30, y: 0.04, width: 0.14, height: 0.04 } },
    ],
  },
  {
    engagementPageId: 32,
    isSuperseded: false,
    retainedPageId: null,
    confidenceLevel: 0.92,
    decisionType: 'Original',
    appliedRuleSet: 'SourceDocs',
    decisionRule: 'ORIGINAL_CORRECTED',
    decisionReason: 'NEWER_VERSION|This is the most recent version||CORRECTED_MARK|Marked as "Corrected"||UPDATED_VALUES|Has updated information',
    reviewRequired: false,
    escalationReason: null,
    documentRef: { pdfPath: PDF_PATH, pageNumber: 32, formType: '1099-DIV', formLabel: '1099-DIV (ExxonMobil) - Corrected', imagePath: IMG['1099-div-corrected'] },
    comparedValues: [
      { field: 'Payer Name', valueA: 'EXXON MOBIL CORPORATION', valueB: 'EXXON MOBIL CORPORATION', match: true, category: 'Payer Info', cropA: { x: 0.05, y: 0.12, width: 0.42, height: 0.04 }, cropB: { x: 0.05, y: 0.12, width: 0.42, height: 0.04 } },
      { field: 'Payer (Transfer Agent)', valueA: 'COMPUTERSHARE', valueB: 'COMPUTERSHARE', match: true, category: 'Payer Info', cropA: { x: 0.05, y: 0.17, width: 0.42, height: 0.04 }, cropB: { x: 0.05, y: 0.17, width: 0.42, height: 0.04 } },
      { field: 'Recipient Name', valueA: 'JILL ANDERSON', valueB: 'JILL ANDERSON', match: true, category: 'Recipient Info', cropA: { x: 0.05, y: 0.24, width: 0.42, height: 0.04 }, cropB: { x: 0.05, y: 0.24, width: 0.42, height: 0.04 } },
      { field: 'Recipient SSN', valueA: '***-**-1234', valueB: '***-**-1234', match: true, category: 'Recipient Info', cropA: { x: 0.05, y: 0.29, width: 0.25, height: 0.04 }, cropB: { x: 0.05, y: 0.29, width: 0.25, height: 0.04 } },
      { field: 'Total Ordinary Dividends (Box 1a)', valueA: '$3,285.60', valueB: '$3,412.80', match: false, category: 'Income', cropA: { x: 0.52, y: 0.32, width: 0.44, height: 0.05 }, cropB: { x: 0.52, y: 0.32, width: 0.44, height: 0.05 } },
      { field: 'Qualified Dividends (Box 1b)', valueA: '$2,890.40', valueB: '$3,012.50', match: false, category: 'Income', cropA: { x: 0.52, y: 0.38, width: 0.44, height: 0.05 }, cropB: { x: 0.52, y: 0.38, width: 0.44, height: 0.05 } },
      { field: 'Document Number', valueA: 'D04018', valueB: 'D04018-C', match: false, category: 'Document', cropA: { x: 0.72, y: 0.06, width: 0.24, height: 0.04 }, cropB: { x: 0.72, y: 0.06, width: 0.24, height: 0.04 } },
      { field: 'Corrected', valueA: 'No', valueB: 'Yes', match: false, category: 'Document', cropA: { x: 0.30, y: 0.04, width: 0.14, height: 0.04 }, cropB: { x: 0.30, y: 0.04, width: 0.14, height: 0.04 } },
    ],
  },
  // ── 1099-DIV (ExxonMobil) ── page 3 of 3: earliest draft also superseded
  {
    engagementPageId: 17,
    isSuperseded: true,
    retainedPageId: 32,
    confidenceLevel: 0.92,
    decisionType: 'Superseded',
    appliedRuleSet: 'SourceDocs',
    decisionRule: 'SUPERSEDED_BY_CORRECTED',
    decisionReason: 'EARLIEST_VERSION|This is the earliest draft||SAME_RECIPIENT|Documents match the same person||REPLACED_TWICE|Replaced first by page 21, then by page 32',
    reviewRequired: false,
    escalationReason: null,
    documentRef: { pdfPath: PDF_PATH, pageNumber: 17, formType: '1099-DIV', formLabel: '1099-DIV (ExxonMobil) - Draft', imagePath: IMG['1099-div-draft'] },
    comparedValues: [
      { field: 'Payer Name', valueA: 'EXXON MOBIL CORPORATION', valueB: 'EXXON MOBIL CORPORATION', match: true, category: 'Payer Info', cropA: { x: 0.05, y: 0.12, width: 0.42, height: 0.04 }, cropB: { x: 0.05, y: 0.12, width: 0.42, height: 0.04 } },
      { field: 'Payer (Transfer Agent)', valueA: 'COMPUTERSHARE', valueB: 'COMPUTERSHARE', match: true, category: 'Payer Info', cropA: { x: 0.05, y: 0.17, width: 0.42, height: 0.04 }, cropB: { x: 0.05, y: 0.17, width: 0.42, height: 0.04 } },
      { field: 'Recipient Name', valueA: 'JILL ANDERSON', valueB: 'JILL ANDERSON', match: true, category: 'Recipient Info', cropA: { x: 0.05, y: 0.24, width: 0.42, height: 0.04 }, cropB: { x: 0.05, y: 0.24, width: 0.42, height: 0.04 } },
      { field: 'Recipient SSN', valueA: '***-**-1234', valueB: '***-**-1234', match: true, category: 'Recipient Info', cropA: { x: 0.05, y: 0.29, width: 0.25, height: 0.04 }, cropB: { x: 0.05, y: 0.29, width: 0.25, height: 0.04 } },
      { field: 'Total Ordinary Dividends (Box 1a)', valueA: '$3,100.00', valueB: '$3,412.80', match: false, category: 'Income', cropA: { x: 0.52, y: 0.32, width: 0.44, height: 0.05 }, cropB: { x: 0.52, y: 0.32, width: 0.44, height: 0.05 } },
      { field: 'Qualified Dividends (Box 1b)', valueA: '$2,720.00', valueB: '$3,012.50', match: false, category: 'Income', cropA: { x: 0.52, y: 0.38, width: 0.44, height: 0.05 }, cropB: { x: 0.52, y: 0.38, width: 0.44, height: 0.05 } },
      { field: 'Document Number', valueA: 'D04018-DRAFT', valueB: 'D04018-C', match: false, category: 'Document', cropA: { x: 0.72, y: 0.06, width: 0.24, height: 0.04 }, cropB: { x: 0.72, y: 0.06, width: 0.24, height: 0.04 } },
      { field: 'Corrected', valueA: 'No', valueB: 'Yes', match: false, category: 'Document', cropA: { x: 0.30, y: 0.04, width: 0.14, height: 0.04 }, cropB: { x: 0.30, y: 0.04, width: 0.14, height: 0.04 } },
    ],
  },

  // ── W-2 (WHYNOT STOP INC) ── 1 Original + 1 Superseded  (HIGH 0.95)
  {
    engagementPageId: 5,
    isSuperseded: true,
    retainedPageId: 14,
    confidenceLevel: 0.95,
    decisionType: 'Superseded',
    appliedRuleSet: 'SourceDocs',
    decisionRule: 'SUPERSEDED_BY_CORRECTED',
    decisionReason: 'NEWER_VERSION|Page 14 replaces page 5||SAME_RECIPIENT|Employee name matches||UPDATED_VALUES|Wage amount corrected',
    reviewRequired: false,
    escalationReason: null,
    documentRef: { pdfPath: PDF_PATH, pageNumber: 5, formType: 'W-2', formLabel: 'W-2 (WHYNOT STOP INC)', imagePath: IMG['w2'] },
    comparedValues: [
      { field: 'Employer Name', valueA: 'WHYNOT STOP INC', valueB: 'WHYNOT STOP INC', match: true, category: 'Employer Info', cropA: { x: 0.05, y: 0.12, width: 0.42, height: 0.04 }, cropB: { x: 0.05, y: 0.12, width: 0.42, height: 0.04 } },
      { field: 'Employer EIN', valueA: '53-XXXXXXX', valueB: '53-XXXXXXX', match: true, category: 'Employer Info', cropA: { x: 0.05, y: 0.17, width: 0.25, height: 0.04 }, cropB: { x: 0.05, y: 0.17, width: 0.25, height: 0.04 } },
      { field: 'Employee Name', valueA: 'JILL ANDERSON', valueB: 'JILL ANDERSON', match: true, category: 'Employee Info', cropA: { x: 0.05, y: 0.24, width: 0.42, height: 0.04 }, cropB: { x: 0.05, y: 0.24, width: 0.42, height: 0.04 } },
      { field: 'Employee SSN', valueA: '***-**-1234', valueB: '***-**-1234', match: true, category: 'Employee Info', cropA: { x: 0.05, y: 0.29, width: 0.25, height: 0.04 }, cropB: { x: 0.05, y: 0.29, width: 0.25, height: 0.04 } },
      { field: 'Wages (Box 1)', valueA: '$62,400.00', valueB: '$63,150.00', match: false, category: 'Income', cropA: { x: 0.52, y: 0.32, width: 0.44, height: 0.05 }, cropB: { x: 0.52, y: 0.32, width: 0.44, height: 0.05 } },
      { field: 'Federal Tax Withheld (Box 2)', valueA: '$9,360.00', valueB: '$9,472.50', match: false, category: 'Income', cropA: { x: 0.52, y: 0.38, width: 0.44, height: 0.05 }, cropB: { x: 0.52, y: 0.38, width: 0.44, height: 0.05 } },
      { field: 'Corrected', valueA: 'No', valueB: 'Yes', match: false, category: 'Document', cropA: { x: 0.30, y: 0.04, width: 0.14, height: 0.04 }, cropB: { x: 0.30, y: 0.04, width: 0.14, height: 0.04 } },
    ],
  },
  {
    engagementPageId: 14,
    isSuperseded: false,
    retainedPageId: null,
    confidenceLevel: 0.95,
    decisionType: 'Original',
    appliedRuleSet: 'SourceDocs',
    decisionRule: 'ORIGINAL_CORRECTED',
    decisionReason: 'NEWER_VERSION|This is the corrected version||CORRECTED_MARK|Marked as "Corrected"||UPDATED_VALUES|Has updated wage information',
    reviewRequired: false,
    escalationReason: null,
    documentRef: { pdfPath: PDF_PATH, pageNumber: 14, formType: 'W-2', formLabel: 'W-2 (WHYNOT STOP INC) - Corrected', imagePath: IMG['w2-corrected'] },
    comparedValues: [
      { field: 'Employer Name', valueA: 'WHYNOT STOP INC', valueB: 'WHYNOT STOP INC', match: true, category: 'Employer Info', cropA: { x: 0.05, y: 0.12, width: 0.42, height: 0.04 }, cropB: { x: 0.05, y: 0.12, width: 0.42, height: 0.04 } },
      { field: 'Employer EIN', valueA: '53-XXXXXXX', valueB: '53-XXXXXXX', match: true, category: 'Employer Info', cropA: { x: 0.05, y: 0.17, width: 0.25, height: 0.04 }, cropB: { x: 0.05, y: 0.17, width: 0.25, height: 0.04 } },
      { field: 'Employee Name', valueA: 'JILL ANDERSON', valueB: 'JILL ANDERSON', match: true, category: 'Employee Info', cropA: { x: 0.05, y: 0.24, width: 0.42, height: 0.04 }, cropB: { x: 0.05, y: 0.24, width: 0.42, height: 0.04 } },
      { field: 'Employee SSN', valueA: '***-**-1234', valueB: '***-**-1234', match: true, category: 'Employee Info', cropA: { x: 0.05, y: 0.29, width: 0.25, height: 0.04 }, cropB: { x: 0.05, y: 0.29, width: 0.25, height: 0.04 } },
      { field: 'Wages (Box 1)', valueA: '$62,400.00', valueB: '$63,150.00', match: false, category: 'Income', cropA: { x: 0.52, y: 0.32, width: 0.44, height: 0.05 }, cropB: { x: 0.52, y: 0.32, width: 0.44, height: 0.05 } },
      { field: 'Federal Tax Withheld (Box 2)', valueA: '$9,360.00', valueB: '$9,472.50', match: false, category: 'Income', cropA: { x: 0.52, y: 0.38, width: 0.44, height: 0.05 }, cropB: { x: 0.52, y: 0.38, width: 0.44, height: 0.05 } },
      { field: 'Corrected', valueA: 'No', valueB: 'Yes', match: false, category: 'Document', cropA: { x: 0.30, y: 0.04, width: 0.14, height: 0.04 }, cropB: { x: 0.30, y: 0.04, width: 0.14, height: 0.04 } },
    ],
  },

  // ── 1099-INT (Chase Bank) ── 1 Original + 1 Superseded  (MODERATE 0.78)
  {
    engagementPageId: 8,
    isSuperseded: true,
    retainedPageId: 22,
    confidenceLevel: 0.78,
    decisionType: 'Superseded',
    appliedRuleSet: 'SourceDocs',
    decisionRule: 'NEAR_MATCH_AMOUNT_DIFF',
    decisionReason: 'SAME_PAYER|Same bank on both forms||SAME_RECIPIENT|Recipient matches||AMOUNT_DIFF|Interest amounts differ by $142',
    reviewRequired: true,
    escalationReason: 'Interest amounts differ. Could be a corrected version or a different account.',
    documentRef: { pdfPath: PDF_PATH, pageNumber: 8, formType: '1099-INT', formLabel: '1099-INT (Chase Bank)', imagePath: IMG['1099-int'] },
    comparedValues: [
      { field: 'Payer Name', valueA: 'JPMORGAN CHASE BANK NA', valueB: 'JPMORGAN CHASE BANK NA', match: true, category: 'Payer Info', cropA: { x: 0.05, y: 0.12, width: 0.42, height: 0.04 }, cropB: { x: 0.05, y: 0.12, width: 0.42, height: 0.04 } },
      { field: 'Payer TIN', valueA: '13-4994650', valueB: '13-4994650', match: true, category: 'Payer Info', cropA: { x: 0.05, y: 0.17, width: 0.25, height: 0.04 }, cropB: { x: 0.05, y: 0.17, width: 0.25, height: 0.04 } },
      { field: 'Recipient Name', valueA: 'JILL ANDERSON', valueB: 'JILL ANDERSON', match: true, category: 'Recipient Info', cropA: { x: 0.05, y: 0.24, width: 0.42, height: 0.04 }, cropB: { x: 0.05, y: 0.24, width: 0.42, height: 0.04 } },
      { field: 'Recipient SSN', valueA: '***-**-1234', valueB: '***-**-1234', match: true, category: 'Recipient Info', cropA: { x: 0.05, y: 0.29, width: 0.25, height: 0.04 }, cropB: { x: 0.05, y: 0.29, width: 0.25, height: 0.04 } },
      { field: 'Interest Income (Box 1)', valueA: '$1,845.00', valueB: '$1,987.00', match: false, category: 'Income', cropA: { x: 0.52, y: 0.32, width: 0.44, height: 0.05 }, cropB: { x: 0.52, y: 0.32, width: 0.44, height: 0.05 } },
      { field: 'Account Number', valueA: '****8821', valueB: '****8821', match: true, category: 'Account', cropA: { x: 0.52, y: 0.44, width: 0.44, height: 0.04 }, cropB: { x: 0.52, y: 0.44, width: 0.44, height: 0.04 } },
    ],
  },
  {
    engagementPageId: 22,
    isSuperseded: false,
    retainedPageId: null,
    confidenceLevel: 0.78,
    decisionType: 'Original',
    appliedRuleSet: 'SourceDocs',
    decisionRule: 'NEAR_MATCH_NEWER',
    decisionReason: 'SAME_PAYER|Same bank on both||LATER_DATE|This form has a later postmark||AMOUNT_DIFF|Higher interest amount suggests updated reporting',
    reviewRequired: true,
    escalationReason: 'Interest amounts differ. Could be a corrected version or a different account.',
    documentRef: { pdfPath: PDF_PATH, pageNumber: 22, formType: '1099-INT', formLabel: '1099-INT (Chase Bank) - Updated', imagePath: IMG['1099-int-updated'] },
    comparedValues: [
      { field: 'Payer Name', valueA: 'JPMORGAN CHASE BANK NA', valueB: 'JPMORGAN CHASE BANK NA', match: true, category: 'Payer Info', cropA: { x: 0.05, y: 0.12, width: 0.42, height: 0.04 }, cropB: { x: 0.05, y: 0.12, width: 0.42, height: 0.04 } },
      { field: 'Payer TIN', valueA: '13-4994650', valueB: '13-4994650', match: true, category: 'Payer Info', cropA: { x: 0.05, y: 0.17, width: 0.25, height: 0.04 }, cropB: { x: 0.05, y: 0.17, width: 0.25, height: 0.04 } },
      { field: 'Recipient Name', valueA: 'JILL ANDERSON', valueB: 'JILL ANDERSON', match: true, category: 'Recipient Info', cropA: { x: 0.05, y: 0.24, width: 0.42, height: 0.04 }, cropB: { x: 0.05, y: 0.24, width: 0.42, height: 0.04 } },
      { field: 'Recipient SSN', valueA: '***-**-1234', valueB: '***-**-1234', match: true, category: 'Recipient Info', cropA: { x: 0.05, y: 0.29, width: 0.25, height: 0.04 }, cropB: { x: 0.05, y: 0.29, width: 0.25, height: 0.04 } },
      { field: 'Interest Income (Box 1)', valueA: '$1,845.00', valueB: '$1,987.00', match: false, category: 'Income', cropA: { x: 0.52, y: 0.32, width: 0.44, height: 0.05 }, cropB: { x: 0.52, y: 0.32, width: 0.44, height: 0.05 } },
      { field: 'Account Number', valueA: '****8821', valueB: '****8821', match: true, category: 'Account', cropA: { x: 0.52, y: 0.44, width: 0.44, height: 0.04 }, cropB: { x: 0.52, y: 0.44, width: 0.44, height: 0.04 } },
    ],
  },

  // ── 1099-B (Charles Schwab) ── 1 Original + 1 Superseded  (MODERATE 0.82)
  {
    engagementPageId: 11,
    isSuperseded: true,
    retainedPageId: 38,
    confidenceLevel: 0.82,
    decisionType: 'Superseded',
    appliedRuleSet: 'ConsolidatedStatements',
    decisionRule: 'CONSOLIDATED_SUPERSEDED',
    decisionReason: 'SAME_BROKER|Same brokerage on both||SAME_RECIPIENT|Recipient matches||LATER_STATEMENT|Later consolidated statement replaces earlier one',
    reviewRequired: true,
    escalationReason: 'Consolidated statement from same broker. Proceeds and cost basis differ.',
    documentRef: { pdfPath: PDF_PATH, pageNumber: 11, formType: '1099-B', formLabel: '1099-B (Charles Schwab)', imagePath: IMG['1099-b'] },
    comparedValues: [
      { field: 'Broker Name', valueA: 'CHARLES SCHWAB & CO INC', valueB: 'CHARLES SCHWAB & CO INC', match: true, category: 'Broker Info', cropA: { x: 0.05, y: 0.12, width: 0.42, height: 0.04 }, cropB: { x: 0.05, y: 0.12, width: 0.42, height: 0.04 } },
      { field: 'Account Number', valueA: '****4592', valueB: '****4592', match: true, category: 'Broker Info', cropA: { x: 0.05, y: 0.17, width: 0.25, height: 0.04 }, cropB: { x: 0.05, y: 0.17, width: 0.25, height: 0.04 } },
      { field: 'Recipient Name', valueA: 'JILL ANDERSON', valueB: 'JILL ANDERSON', match: true, category: 'Recipient Info', cropA: { x: 0.05, y: 0.24, width: 0.42, height: 0.04 }, cropB: { x: 0.05, y: 0.24, width: 0.42, height: 0.04 } },
      { field: 'Total Proceeds', valueA: '$45,200.00', valueB: '$47,850.00', match: false, category: 'Capital Gains', cropA: { x: 0.52, y: 0.32, width: 0.44, height: 0.05 }, cropB: { x: 0.52, y: 0.32, width: 0.44, height: 0.05 } },
      { field: 'Total Cost Basis', valueA: '$38,100.00', valueB: '$39,500.00', match: false, category: 'Capital Gains', cropA: { x: 0.52, y: 0.38, width: 0.44, height: 0.05 }, cropB: { x: 0.52, y: 0.38, width: 0.44, height: 0.05 } },
      { field: 'Statement Date', valueA: 'Feb 15, 2024', valueB: 'Mar 15, 2024', match: false, category: 'Document', cropA: { x: 0.72, y: 0.06, width: 0.24, height: 0.04 }, cropB: { x: 0.72, y: 0.06, width: 0.24, height: 0.04 } },
    ],
  },
  {
    engagementPageId: 38,
    isSuperseded: false,
    retainedPageId: null,
    confidenceLevel: 0.82,
    decisionType: 'Original',
    appliedRuleSet: 'ConsolidatedStatements',
    decisionRule: 'CONSOLIDATED_LATEST',
    decisionReason: 'SAME_BROKER|Same brokerage||LATER_STATEMENT|This is the final consolidated statement||UPDATED_VALUES|Contains corrected proceeds and cost basis',
    reviewRequired: true,
    escalationReason: 'Consolidated statement from same broker. Proceeds and cost basis differ.',
    documentRef: { pdfPath: PDF_PATH, pageNumber: 38, formType: '1099-B', formLabel: '1099-B (Charles Schwab) - Final', imagePath: IMG['1099-b-final'] },
    comparedValues: [
      { field: 'Broker Name', valueA: 'CHARLES SCHWAB & CO INC', valueB: 'CHARLES SCHWAB & CO INC', match: true, category: 'Broker Info', cropA: { x: 0.05, y: 0.12, width: 0.42, height: 0.04 }, cropB: { x: 0.05, y: 0.12, width: 0.42, height: 0.04 } },
      { field: 'Account Number', valueA: '****4592', valueB: '****4592', match: true, category: 'Broker Info', cropA: { x: 0.05, y: 0.17, width: 0.25, height: 0.04 }, cropB: { x: 0.05, y: 0.17, width: 0.25, height: 0.04 } },
      { field: 'Recipient Name', valueA: 'JILL ANDERSON', valueB: 'JILL ANDERSON', match: true, category: 'Recipient Info', cropA: { x: 0.05, y: 0.24, width: 0.42, height: 0.04 }, cropB: { x: 0.05, y: 0.24, width: 0.42, height: 0.04 } },
      { field: 'Total Proceeds', valueA: '$45,200.00', valueB: '$47,850.00', match: false, category: 'Capital Gains', cropA: { x: 0.52, y: 0.32, width: 0.44, height: 0.05 }, cropB: { x: 0.52, y: 0.32, width: 0.44, height: 0.05 } },
      { field: 'Total Cost Basis', valueA: '$38,100.00', valueB: '$39,500.00', match: false, category: 'Capital Gains', cropA: { x: 0.52, y: 0.38, width: 0.44, height: 0.05 }, cropB: { x: 0.52, y: 0.38, width: 0.44, height: 0.05 } },
      { field: 'Statement Date', valueA: 'Feb 15, 2024', valueB: 'Mar 15, 2024', match: false, category: 'Document', cropA: { x: 0.72, y: 0.06, width: 0.24, height: 0.04 }, cropB: { x: 0.72, y: 0.06, width: 0.24, height: 0.04 } },
    ],
  },

  // ── 1099-B (Charles Schwab) ── page 3 of 3: preliminary statement also superseded
  {
    engagementPageId: 7,
    isSuperseded: true,
    retainedPageId: 38,
    confidenceLevel: 0.82,
    decisionType: 'Superseded',
    appliedRuleSet: 'ConsolidatedStatements',
    decisionRule: 'CONSOLIDATED_PRELIMINARY',
    decisionReason: 'SAME_BROKER|Same brokerage||EARLIEST_STATEMENT|Preliminary statement from Jan||REPLACED_BY_FINAL|Replaced by final consolidated on Mar 15',
    reviewRequired: true,
    escalationReason: 'Preliminary consolidated statement. Replaced by two later versions.',
    documentRef: { pdfPath: PDF_PATH, pageNumber: 7, formType: '1099-B', formLabel: '1099-B (Charles Schwab) - Preliminary', imagePath: IMG['1099-b-preliminary'] },
    comparedValues: [
      { field: 'Broker Name', valueA: 'CHARLES SCHWAB & CO INC', valueB: 'CHARLES SCHWAB & CO INC', match: true, category: 'Broker Info', cropA: { x: 0.05, y: 0.12, width: 0.42, height: 0.04 }, cropB: { x: 0.05, y: 0.12, width: 0.42, height: 0.04 } },
      { field: 'Account Number', valueA: '****4592', valueB: '****4592', match: true, category: 'Broker Info', cropA: { x: 0.05, y: 0.17, width: 0.25, height: 0.04 }, cropB: { x: 0.05, y: 0.17, width: 0.25, height: 0.04 } },
      { field: 'Recipient Name', valueA: 'JILL ANDERSON', valueB: 'JILL ANDERSON', match: true, category: 'Recipient Info', cropA: { x: 0.05, y: 0.24, width: 0.42, height: 0.04 }, cropB: { x: 0.05, y: 0.24, width: 0.42, height: 0.04 } },
      { field: 'Total Proceeds', valueA: '$42,100.00', valueB: '$47,850.00', match: false, category: 'Capital Gains', cropA: { x: 0.52, y: 0.32, width: 0.44, height: 0.05 }, cropB: { x: 0.52, y: 0.32, width: 0.44, height: 0.05 } },
      { field: 'Total Cost Basis', valueA: '$36,800.00', valueB: '$39,500.00', match: false, category: 'Capital Gains', cropA: { x: 0.52, y: 0.38, width: 0.44, height: 0.05 }, cropB: { x: 0.52, y: 0.38, width: 0.44, height: 0.05 } },
      { field: 'Statement Date', valueA: 'Jan 31, 2024', valueB: 'Mar 15, 2024', match: false, category: 'Document', cropA: { x: 0.72, y: 0.06, width: 0.24, height: 0.04 }, cropB: { x: 0.72, y: 0.06, width: 0.24, height: 0.04 } },
    ],
  },

  // ── Schedule K-1 (Chapman Trust) ── 1 Original + 1 Superseded  (LOW 0.58)
  {
    engagementPageId: 15,
    isSuperseded: true,
    retainedPageId: 42,
    confidenceLevel: 0.58,
    decisionType: 'Superseded',
    appliedRuleSet: 'SourceDocs',
    decisionRule: 'UNCERTAIN_MATCH',
    decisionReason: 'SAME_TRUST|Same trust EIN||AMOUNT_DIFF|Several income categories differ significantly||UNCERTAIN|May be from different reporting periods',
    reviewRequired: true,
    escalationReason: 'Confidence below threshold. Multiple income categories differ. Could be amended K-1 or different distribution period.',
    documentRef: { pdfPath: PDF_PATH, pageNumber: 15, formType: 'Schedule K-1', formLabel: 'K-1 (Chapman Trust)', imagePath: IMG['k1'] },
    comparedValues: [
      { field: 'Trust Name', valueA: 'CHAPMAN IRREVOCABLE TRUST', valueB: 'CHAPMAN IRREVOCABLE TRUST', match: true, category: 'Entity Info', cropA: { x: 0.05, y: 0.12, width: 0.42, height: 0.04 }, cropB: { x: 0.05, y: 0.12, width: 0.42, height: 0.04 } },
      { field: 'Trust EIN', valueA: '34-3353535', valueB: '34-3353535', match: true, category: 'Entity Info', cropA: { x: 0.05, y: 0.17, width: 0.25, height: 0.04 }, cropB: { x: 0.05, y: 0.17, width: 0.25, height: 0.04 } },
      { field: 'Beneficiary Name', valueA: 'JILL ANDERSON', valueB: 'JILL ANDERSON', match: true, category: 'Beneficiary Info', cropA: { x: 0.05, y: 0.24, width: 0.42, height: 0.04 }, cropB: { x: 0.05, y: 0.24, width: 0.42, height: 0.04 } },
      { field: 'Ordinary Business Income', valueA: '$8,748.00', valueB: '$12,200.00', match: false, category: 'Income', cropA: { x: 0.52, y: 0.32, width: 0.44, height: 0.05 }, cropB: { x: 0.52, y: 0.32, width: 0.44, height: 0.05 } },
      { field: 'Interest Income', valueA: '$2,575.00', valueB: '$2,575.00', match: true, category: 'Income', cropA: { x: 0.52, y: 0.38, width: 0.44, height: 0.05 }, cropB: { x: 0.52, y: 0.38, width: 0.44, height: 0.05 } },
      { field: 'Ordinary Dividends', valueA: '$62,565.00', valueB: '$58,900.00', match: false, category: 'Income', cropA: { x: 0.52, y: 0.44, width: 0.44, height: 0.05 }, cropB: { x: 0.52, y: 0.44, width: 0.44, height: 0.05 } },
      { field: 'Net Rental Income', valueA: '$4,200.00', valueB: '$0.00', match: false, category: 'Income', cropA: { x: 0.52, y: 0.50, width: 0.44, height: 0.05 }, cropB: { x: 0.52, y: 0.50, width: 0.44, height: 0.05 } },
    ],
  },
  {
    engagementPageId: 42,
    isSuperseded: false,
    retainedPageId: null,
    confidenceLevel: 0.58,
    decisionType: 'Original',
    appliedRuleSet: 'SourceDocs',
    decisionRule: 'UNCERTAIN_NEWER',
    decisionReason: 'SAME_TRUST|Same trust EIN||LATER_DATE|Later filing date||AMOUNT_DIFF|Multiple income lines changed substantially',
    reviewRequired: true,
    escalationReason: 'Confidence below threshold. Multiple income categories differ. Could be amended K-1 or different distribution period.',
    documentRef: { pdfPath: PDF_PATH, pageNumber: 42, formType: 'Schedule K-1', formLabel: 'K-1 (Chapman Trust) - Amended', imagePath: IMG['k1-amended'] },
    comparedValues: [
      { field: 'Trust Name', valueA: 'CHAPMAN IRREVOCABLE TRUST', valueB: 'CHAPMAN IRREVOCABLE TRUST', match: true, category: 'Entity Info', cropA: { x: 0.05, y: 0.12, width: 0.42, height: 0.04 }, cropB: { x: 0.05, y: 0.12, width: 0.42, height: 0.04 } },
      { field: 'Trust EIN', valueA: '34-3353535', valueB: '34-3353535', match: true, category: 'Entity Info', cropA: { x: 0.05, y: 0.17, width: 0.25, height: 0.04 }, cropB: { x: 0.05, y: 0.17, width: 0.25, height: 0.04 } },
      { field: 'Beneficiary Name', valueA: 'JILL ANDERSON', valueB: 'JILL ANDERSON', match: true, category: 'Beneficiary Info', cropA: { x: 0.05, y: 0.24, width: 0.42, height: 0.04 }, cropB: { x: 0.05, y: 0.24, width: 0.42, height: 0.04 } },
      { field: 'Ordinary Business Income', valueA: '$8,748.00', valueB: '$12,200.00', match: false, category: 'Income', cropA: { x: 0.52, y: 0.32, width: 0.44, height: 0.05 }, cropB: { x: 0.52, y: 0.32, width: 0.44, height: 0.05 } },
      { field: 'Interest Income', valueA: '$2,575.00', valueB: '$2,575.00', match: true, category: 'Income', cropA: { x: 0.52, y: 0.38, width: 0.44, height: 0.05 }, cropB: { x: 0.52, y: 0.38, width: 0.44, height: 0.05 } },
      { field: 'Ordinary Dividends', valueA: '$62,565.00', valueB: '$58,900.00', match: false, category: 'Income', cropA: { x: 0.52, y: 0.44, width: 0.44, height: 0.05 }, cropB: { x: 0.52, y: 0.44, width: 0.44, height: 0.05 } },
      { field: 'Net Rental Income', valueA: '$4,200.00', valueB: '$0.00', match: false, category: 'Income', cropA: { x: 0.52, y: 0.50, width: 0.44, height: 0.05 }, cropB: { x: 0.52, y: 0.50, width: 0.44, height: 0.05 } },
    ],
  },

  // ── 1099-R (Fidelity) ── 1 Original + 1 Superseded  (LOW 0.65)
  {
    engagementPageId: 19,
    isSuperseded: true,
    retainedPageId: 44,
    confidenceLevel: 0.65,
    decisionType: 'Superseded',
    appliedRuleSet: 'SourceDocs',
    decisionRule: 'PARTIAL_MATCH',
    decisionReason: 'SAME_PAYER|Same custodian||SAME_RECIPIENT|Recipient SSN matches||DIST_CODE_DIFF|Distribution code differs between versions',
    reviewRequired: true,
    escalationReason: 'Distribution codes differ (7 vs 1). This may be a correction or a separate distribution event.',
    documentRef: { pdfPath: PDF_PATH, pageNumber: 19, formType: '1099-R', formLabel: '1099-R (Fidelity)', imagePath: IMG['1099-r'] },
    comparedValues: [
      { field: 'Payer Name', valueA: 'FIDELITY INVESTMENTS', valueB: 'FIDELITY INVESTMENTS', match: true, category: 'Payer Info', cropA: { x: 0.05, y: 0.12, width: 0.42, height: 0.04 }, cropB: { x: 0.05, y: 0.12, width: 0.42, height: 0.04 } },
      { field: 'Payer TIN', valueA: '04-3523567', valueB: '04-3523567', match: true, category: 'Payer Info', cropA: { x: 0.05, y: 0.17, width: 0.25, height: 0.04 }, cropB: { x: 0.05, y: 0.17, width: 0.25, height: 0.04 } },
      { field: 'Recipient Name', valueA: 'JILL ANDERSON', valueB: 'JILL ANDERSON', match: true, category: 'Recipient Info', cropA: { x: 0.05, y: 0.24, width: 0.42, height: 0.04 }, cropB: { x: 0.05, y: 0.24, width: 0.42, height: 0.04 } },
      { field: 'Gross Distribution (Box 1)', valueA: '$15,000.00', valueB: '$15,000.00', match: true, category: 'Distribution', cropA: { x: 0.52, y: 0.32, width: 0.44, height: 0.05 }, cropB: { x: 0.52, y: 0.32, width: 0.44, height: 0.05 } },
      { field: 'Taxable Amount (Box 2a)', valueA: '$15,000.00', valueB: '$12,500.00', match: false, category: 'Distribution', cropA: { x: 0.52, y: 0.38, width: 0.44, height: 0.05 }, cropB: { x: 0.52, y: 0.38, width: 0.44, height: 0.05 } },
      { field: 'Distribution Code (Box 7)', valueA: '7', valueB: '1', match: false, category: 'Distribution', cropA: { x: 0.52, y: 0.50, width: 0.20, height: 0.04 }, cropB: { x: 0.52, y: 0.50, width: 0.20, height: 0.04 } },
      { field: 'IRA/SEP/SIMPLE', valueA: 'Yes', valueB: 'Yes', match: true, category: 'Account', cropA: { x: 0.52, y: 0.56, width: 0.20, height: 0.04 }, cropB: { x: 0.52, y: 0.56, width: 0.20, height: 0.04 } },
    ],
  },
  {
    engagementPageId: 44,
    isSuperseded: false,
    retainedPageId: null,
    confidenceLevel: 0.65,
    decisionType: 'Original',
    appliedRuleSet: 'SourceDocs',
    decisionRule: 'PARTIAL_MATCH_NEWER',
    decisionReason: 'SAME_PAYER|Same custodian||LATER_DATE|More recent version||DIST_CODE_DIFF|Distribution code changed - may indicate correction',
    reviewRequired: true,
    escalationReason: 'Distribution codes differ (7 vs 1). This may be a correction or a separate distribution event.',
    documentRef: { pdfPath: PDF_PATH, pageNumber: 44, formType: '1099-R', formLabel: '1099-R (Fidelity) - Corrected', imagePath: IMG['1099-r-corrected'] },
    comparedValues: [
      { field: 'Payer Name', valueA: 'FIDELITY INVESTMENTS', valueB: 'FIDELITY INVESTMENTS', match: true, category: 'Payer Info', cropA: { x: 0.05, y: 0.12, width: 0.42, height: 0.04 }, cropB: { x: 0.05, y: 0.12, width: 0.42, height: 0.04 } },
      { field: 'Payer TIN', valueA: '04-3523567', valueB: '04-3523567', match: true, category: 'Payer Info', cropA: { x: 0.05, y: 0.17, width: 0.25, height: 0.04 }, cropB: { x: 0.05, y: 0.17, width: 0.25, height: 0.04 } },
      { field: 'Recipient Name', valueA: 'JILL ANDERSON', valueB: 'JILL ANDERSON', match: true, category: 'Recipient Info', cropA: { x: 0.05, y: 0.24, width: 0.42, height: 0.04 }, cropB: { x: 0.05, y: 0.24, width: 0.42, height: 0.04 } },
      { field: 'Gross Distribution (Box 1)', valueA: '$15,000.00', valueB: '$15,000.00', match: true, category: 'Distribution', cropA: { x: 0.52, y: 0.32, width: 0.44, height: 0.05 }, cropB: { x: 0.52, y: 0.32, width: 0.44, height: 0.05 } },
      { field: 'Taxable Amount (Box 2a)', valueA: '$15,000.00', valueB: '$12,500.00', match: false, category: 'Distribution', cropA: { x: 0.52, y: 0.38, width: 0.44, height: 0.05 }, cropB: { x: 0.52, y: 0.38, width: 0.44, height: 0.05 } },
      { field: 'Distribution Code (Box 7)', valueA: '7', valueB: '1', match: false, category: 'Distribution', cropA: { x: 0.52, y: 0.50, width: 0.20, height: 0.04 }, cropB: { x: 0.52, y: 0.50, width: 0.20, height: 0.04 } },
      { field: 'IRA/SEP/SIMPLE', valueA: 'Yes', valueB: 'Yes', match: true, category: 'Account', cropA: { x: 0.52, y: 0.56, width: 0.20, height: 0.04 }, cropB: { x: 0.52, y: 0.56, width: 0.20, height: 0.04 } },
    ],
  },
]

export const duplicateA: DuplicateRecord[] = [
  {
    itemType: 'DUPLICATE_DATA',
    organizerItemId: 'ORG-001',
    sourceReferenceId: 'SRC-001',
    decision: 'DuplicateData',
    matchType: 'DirectAmount',
    confidenceLevel: 0.97,
    appliedRuleSet: 'DUP-DATA',
    decisionRule: 'EXACT_DATA_MATCH',
    decisionReason: 'EXACT_MATCH|Documents match exactly||SAME_DOCUMENT|Same W-2 from same employer||KEEP_ONE|Keep one copy, remove duplicate',
    fieldsCompared: ['SSN', 'EIN', 'WagesAmount', 'FederalWithheld', 'TaxYear'],
    reviewRequired: false,
    escalationReason: null,
    comparedValues: [
      { field: 'Employee SSN', valueA: '***-**-1234', valueB: '***-**-1234', match: true },
      { field: 'Employer EIN', valueA: '53-XXXXXXX', valueB: '53-XXXXXXX', match: true },
      { field: 'Employer Name', valueA: 'WHYNOT STOP INC', valueB: 'WHYNOT STOP INC', match: true },
      { field: 'Employee Address', valueA: '1234 MAIN STREET, DALLAS, TX 75202', valueB: '1234 MAIN STREET, DALLAS, TX 75202', match: true },
      { field: 'Tax Year', valueA: '2024', valueB: '2024', match: true },
    ],
    documentRefA: { pdfPath: PDF_PATH, pageNumber: 1, formType: 'W-2', formLabel: 'W-2 (Source Doc)', imagePath: IMG['w2'] },
    documentRefB: { pdfPath: PDF_PATH, pageNumber: 1, formType: 'W-2', formLabel: 'W-2 (Organizer)', imagePath: IMG['w2'] },
  },
  {
    itemType: 'DUPLICATE_DATA',
    organizerItemId: 'ORG-002',
    sourceReferenceId: 'SRC-002',
    decision: 'DuplicateData',
    matchType: 'DirectAmount',
    confidenceLevel: 0.94,
    appliedRuleSet: 'DUP-DATA',
    decisionRule: 'NEAR_DATA_MATCH',
    decisionReason: 'EXACT_MATCH|Income amounts match exactly||SAME_RECIPIENT|Same person on both documents||KEEP_ONE|Keep one copy, remove duplicate',
    fieldsCompared: ['RecipientTIN', 'PayerTIN', 'OtherIncome', 'TaxYear'],
    reviewRequired: false,
    escalationReason: null,
    comparedValues: [
      { field: 'Recipient Name', valueA: 'JACK ANDERSON', valueB: 'JACK ANDERSON', match: true },
      { field: 'Recipient TIN', valueA: '111-11-1111', valueB: '111-11-1111', match: true },
      { field: 'Payer Name', valueA: 'RICHMONT NORTH AMERICA, INC', valueB: 'RICHMONT NORTH AMERICA, INC', match: true },
      { field: 'Payer TIN', valueA: '13-2852910', valueB: '13-2852910', match: true },
      { field: 'Box 3 (Other Income)', valueA: '$14,921.24', valueB: '$14,921.24', match: true },
    ],
    documentRefA: { pdfPath: PDF_PATH, pageNumber: 4, formType: '1099-MISC', formLabel: '1099-MISC (Source)', imagePath: IMG['1099-misc'] },
    documentRefB: { pdfPath: PDF_PATH, pageNumber: 4, formType: '1099-MISC', formLabel: '1099-MISC (Organizer)', imagePath: IMG['1099-misc'] },
  },
  {
    itemType: 'DUPLICATE_DATA',
    organizerItemId: 'ORG-003',
    sourceReferenceId: 'SRC-003',
    decision: 'NotDuplicateData',
    matchType: 'Other',
    confidenceLevel: 0.99,
    appliedRuleSet: 'DUP-DATA',
    decisionRule: 'DIFFERENT_PAYER',
    decisionReason: 'SAME_DOCUMENT|Different form types||SAME_RECIPIENT|Different people on documents||KEEP_ONE|Not duplicates - keep both',
    fieldsCompared: ['TaxpayerName', 'PayerEIN', 'PayerName', 'FormType'],
    reviewRequired: false,
    escalationReason: null,
    comparedValues: [
      { field: 'Form Type', valueA: 'W-2', valueB: '1099-MISC', match: false },
      { field: 'Recipient', valueA: 'JILL ANDERSON', valueB: 'JACK ANDERSON', match: false },
      { field: 'Payer', valueA: 'WHYNOT STOP INC', valueB: 'RICHMONT NORTH AMERICA, INC', match: false },
      { field: 'Payer TIN', valueA: '53-XXXXXXX', valueB: '13-2852910', match: false },
      { field: 'Address', valueA: '1234 MAIN STREET, DALLAS, TX 75202', valueB: '1234 MAIN STREET, DALLAS, TX 75202', match: true },
    ],
    documentRefA: { pdfPath: PDF_PATH, pageNumber: 1, formType: 'W-2', formLabel: 'W-2 (WHYNOT STOP)', imagePath: IMG['w2'] },
    documentRefB: { pdfPath: PDF_PATH, pageNumber: 4, formType: '1099-MISC', formLabel: '1099-MISC (RICHMONT)', imagePath: IMG['1099-misc'] },
  },
  {
    itemType: 'DUPLICATE_SOURCE_DOC',
    docIdA: 101,
    docIdB: 105,
    decision: 'Duplicate',
    retainDocId: 101,
    confidenceLevel: 0.88,
    appliedRuleSet: 'DUP-SRC',
    decisionRule: 'VISUAL_DOC_MATCH',
    decisionReason: 'EXACT_MATCH|Two copies of the same document||SAME_DOCUMENT|Same W-2 scanned twice||KEEP_ONE|Keep one copy, remove duplicate',
    fieldsCompared: ['PixelHash', 'OCRText', 'PageDimensions', 'EmployerName'],
    reviewRequired: true,
    escalationReason: null,
    comparedValues: [
      { field: 'Employer Name', valueA: 'WHYNOT STOP INC', valueB: 'WHYNOT STOP INC', match: true },
      { field: 'Employee Name', valueA: 'JILL ANDERSON', valueB: 'JILL ANDERSON', match: true },
      { field: 'Pixel Similarity', valueA: '92%', valueB: '92%', match: true },
      { field: 'Page Dimensions', valueA: '8.5 x 11 in', valueB: '8.5 x 11 in', match: true },
      { field: 'Scan Quality', valueA: '300 DPI', valueB: '150 DPI', match: false },
    ],
    documentRefA: { pdfPath: PDF_PATH, pageNumber: 1, formType: 'W-2', formLabel: 'W-2 Scan A', imagePath: IMG['w2'] },
    documentRefB: { pdfPath: PDF_PATH, pageNumber: 2, formType: 'W-2', formLabel: 'W-2 Scan B', imagePath: IMG['w2'] },
  },
  {
    itemType: 'DUPLICATE_SOURCE_DOC',
    docIdA: 102,
    docIdB: 108,
    decision: 'Duplicate',
    retainDocId: 102,
    confidenceLevel: 0.72,
    appliedRuleSet: 'DUP-SRC',
    decisionRule: 'PARTIAL_DOC_MATCH',
    decisionReason: 'SAME_DOCUMENT|Similar documents found||UPDATED_VALUES|Values differ between copies||CORRECTED_MARK|May be a corrected version',
    fieldsCompared: ['PixelHash', 'OCRText', 'FormType', 'TotalIncome'],
    reviewRequired: true,
    escalationReason: null,
    comparedValues: [
      { field: 'Business Name', valueA: 'Jill\'s Craft Shop', valueB: 'Jill\'s Craft Shop', match: true },
      { field: 'Total Income', valueA: '$48,650.00', valueB: '$48,200.00', match: false },
      { field: 'Net Income', valueA: '$28,119.85', valueB: '$33,700.00', match: false },
      { field: 'Form Type', valueA: 'Schedule C', valueB: 'Schedule C', match: true },
    ],
    documentRefA: { pdfPath: PDF_PATH, pageNumber: 3, formType: 'Schedule C', formLabel: 'Sched C (v1)', imagePath: IMG['schedule-c'] },
    documentRefB: { pdfPath: PDF_PATH, pageNumber: 3, formType: 'Schedule C', formLabel: 'Sched C (v2)', imagePath: IMG['schedule-c'] },
  },
  {
    itemType: 'DUPLICATE_CONSOLIDATED_STATEMENT',
    docIdA: 200,
    docIdB: 205,
    decision: 'Duplicate',
    retainDocId: null,
    confidenceLevel: 0.61,
    appliedRuleSet: 'DUP-CS',
    decisionRule: 'UNCERTAIN_DOC_MATCH',
    decisionReason: 'SAME_RECIPIENT|Same trust on both documents||UPDATED_VALUES|Amounts differ between copies||CORRECTED_MARK|May be from different periods',
    fieldsCompared: ['TrustEIN', 'BeneficiaryID', 'InterestIncome', 'Dividends'],
    reviewRequired: true,
    escalationReason: 'Confidence below threshold. Dividend amounts differ by $325. Could be amended K-1 or different reporting period.',
    comparedValues: [
      { field: 'Trust Name', valueA: 'CHAPMAN IRREVOCABLE TRUST', valueB: 'CHAPMAN IRREVOCABLE TRUST', match: true },
      { field: 'Trust EIN', valueA: '34-3353535', valueB: '34-3353535', match: true },
      { field: 'Beneficiary', valueA: 'JILL BAKER FAMILY TRUST', valueB: 'JILL BAKER FAMILY TRUST', match: true },
      { field: 'Interest Income', valueA: '$2,575', valueB: '$2,575', match: true },
      { field: 'Ordinary Dividends', valueA: '$62,565', valueB: '$62,890', match: false },
      { field: 'Business Income', valueA: '$8,748', valueB: '$8,748', match: true },
    ],
    documentRefA: { pdfPath: PDF_PATH, pageNumber: 5, formType: 'K-1', formLabel: 'K-1 (v1)', imagePath: IMG['k1'] },
    documentRefB: { pdfPath: PDF_PATH, pageNumber: 5, formType: 'K-1', formLabel: 'K-1 (v2)', imagePath: IMG['k1'] },
  },
]

export const cfaA: CfaRecord[] = [
  {
    EngagementFaxFormId: 3001,
    ParentEngagementFaxFormId: 1001,
    EngagementPageId: 1,
    ConfidenceLevel: 0.95,
    IsAddForm: false,
    ParentFaxFormDwpCode: 'DWP-100',
    ParentFaxFormId: 1001,
    childFormLabel: 'W-2 (WHYNOT STOP INC)',
    parentFormLabel: 'Form 1040 (Jill Anderson)',
    documentRef: { pdfPath: PDF_PATH, pageNumber: 1, formType: 'W-2', formLabel: 'W-2 (WHYNOT STOP INC)', imagePath: IMG['w2'] },
    comparedValues: [
      { field: 'Employee Name', valueA: 'JILL ANDERSON', valueB: 'JILL ANDERSON (1040 Filer)', match: true },
      { field: 'Employee SSN', valueA: '***-**-1234', valueB: '***-**-1234 (Primary SSN)', match: true },
      { field: 'Tax Year', valueA: '2024', valueB: '2024', match: true },
      { field: 'Employer Address', valueA: '532 MAIN STREET, WATERVILLE, ME 25570', valueB: 'N/A', match: true },
    ],
  },
  {
    EngagementFaxFormId: 3002,
    ParentEngagementFaxFormId: 1001,
    EngagementPageId: 3,
    ConfidenceLevel: 0.92,
    IsAddForm: false,
    ParentFaxFormDwpCode: 'DWP-200',
    ParentFaxFormId: 1001,
    childFormLabel: 'Schedule C (Jill\'s Craft Shop)',
    parentFormLabel: 'Form 1040 (Jill Anderson)',
    documentRef: { pdfPath: PDF_PATH, pageNumber: 3, formType: 'Schedule C', formLabel: 'Schedule C (Jill\'s Craft Shop)', imagePath: IMG['schedule-c'] },
    comparedValues: [
      { field: 'Proprietor Name', valueA: 'JILL ANDERSON', valueB: 'JILL ANDERSON (1040 Filer)', match: true },
      { field: 'Business Name', valueA: 'Jill\'s Craft Shop', valueB: 'N/A', match: true },
      { field: 'Net Income', valueA: '$28,119.85', valueB: '$28,119.85 (Line 12, Sched 1)', match: true },
      { field: 'Craft Sales', valueA: '$41,200.00', valueB: 'N/A', match: true },
      { field: 'Other Sales', valueA: '$7,450.00', valueB: 'N/A', match: true },
    ],
  },
  {
    EngagementFaxFormId: 3003,
    ParentEngagementFaxFormId: 1001,
    EngagementPageId: 4,
    ConfidenceLevel: 0.78,
    IsAddForm: true,
    ParentFaxFormDwpCode: 'DWP-300',
    ParentFaxFormId: 1001,
    childFormLabel: '1099-MISC (RICHMONT NORTH AMERICA)',
    parentFormLabel: 'Form 1040 (Jill Anderson)',
    documentRef: { pdfPath: PDF_PATH, pageNumber: 4, formType: '1099-MISC', formLabel: '1099-MISC (RICHMONT NORTH AMERICA)', imagePath: IMG['1099-misc'] },
    comparedValues: [
      { field: 'Recipient Name', valueA: 'JACK ANDERSON', valueB: 'JILL ANDERSON (1040 Filer)', match: false },
      { field: 'Recipient TIN', valueA: '111-11-1111', valueB: '***-**-1234 (Primary SSN)', match: false },
      { field: 'Address', valueA: '1234 MAIN STREET, DALLAS, TX 75202', valueB: '1234 MAIN STREET, DALLAS, TX 75202', match: true },
      { field: 'Box 3 (Other Income)', valueA: '$14,921.24', valueB: 'N/A', match: true },
    ],
  },
  {
    EngagementFaxFormId: 3004,
    ParentEngagementFaxFormId: 1001,
    EngagementPageId: 5,
    ConfidenceLevel: 0.91,
    IsAddForm: false,
    ParentFaxFormDwpCode: 'DWP-400',
    ParentFaxFormId: 1001,
    childFormLabel: 'K-1 Form 1041 (CHAPMAN IRREVOCABLE TRUST)',
    parentFormLabel: 'Form 1040 (Jill Anderson)',
    documentRef: { pdfPath: PDF_PATH, pageNumber: 5, formType: 'Schedule K-1', formLabel: 'K-1 (CHAPMAN IRREVOCABLE TRUST)', imagePath: IMG['k1'] },
    comparedValues: [
      { field: 'Trust Name', valueA: 'CHAPMAN IRREVOCABLE TRUST', valueB: 'N/A', match: true },
      { field: 'Trust EIN', valueA: '34-3353535', valueB: 'N/A', match: true },
      { field: 'Beneficiary', valueA: 'JILL BAKER FAMILY TRUST', valueB: 'JILL ANDERSON (1040 Filer)', match: false },
      { field: 'Interest Income', valueA: '$2,575', valueB: '$2,575 (Sched B, Line 1)', match: true },
      { field: 'Ordinary Dividends', valueA: '$62,565', valueB: '$62,565 (Sched B, Line 5)', match: true },
      { field: 'Business Income', valueA: '$8,748', valueB: '$8,748 (Sched E, Part III)', match: true },
    ],
  },
]

export const nfrA: NfrRecord[] = [
  {
    EngagementId: 5001,
    EngagementPageId: 1,
    EngagementFormId: 1040,
    EngagementFieldGroupId: 10,
    FieldGroupId: 100,
    EngagementFaxFormId: 6001,
    FaxRowNumber: 1,
    TaxFormInstanceNo: 1,
    ConfidenceLevel: 0.96,
    MatchStatus: true,
    fieldLabel: 'W-2 Wages',
    sourceValue: 'W-2 Box 1 (WHYNOT STOP INC)',
    returnValue: '1040, Line 1a',
    documentRef: { pdfPath: PDF_PATH, pageNumber: 1, formType: 'W-2', formLabel: 'W-2 (WHYNOT STOP INC)', imagePath: IMG['w2'] },
    comparedValues: [
      { field: 'Employer Name', valueA: 'WHYNOT STOP INC', valueB: 'WHYNOT STOP INC', match: true },
      { field: 'Employee Name', valueA: 'JILL ANDERSON', valueB: 'JILL ANDERSON', match: true },
      { field: 'Employee Address', valueA: '1234 MAIN STREET, DALLAS, TX 75202', valueB: '1234 MAIN STREET, DALLAS, TX 75202', match: true },
    ],
  },
  {
    EngagementId: 5001,
    EngagementPageId: 3,
    EngagementFormId: 1040,
    EngagementFieldGroupId: 20,
    FieldGroupId: 200,
    EngagementFaxFormId: 6002,
    FaxRowNumber: 2,
    TaxFormInstanceNo: 1,
    ConfidenceLevel: 0.93,
    MatchStatus: true,
    fieldLabel: 'Schedule C Net Income',
    sourceValue: 'Schedule C, Net Income',
    returnValue: '1040 Schedule 1, Line 3',
    documentRef: { pdfPath: PDF_PATH, pageNumber: 3, formType: 'Schedule C', formLabel: 'Schedule C (Jill\'s Craft Shop)', imagePath: IMG['schedule-c'] },
    comparedValues: [
      { field: 'Business Name', valueA: 'Jill\'s Craft Shop', valueB: 'Jill\'s Craft Shop', match: true },
      { field: 'Total Income', valueA: '$48,650.00', valueB: '$48,650.00', match: true },
      { field: 'Total Expenses', valueA: '$13,080.15', valueB: '$13,080.15', match: true },
      { field: 'Net Income', valueA: '$28,119.85', valueB: '$28,119.85', match: true },
      { field: 'Advertising', valueA: '$1,550.42', valueB: '$1,550.42', match: true },
      { field: 'Legal Fees', valueA: '$1,200.00', valueB: '$1,200.00', match: true },
      { field: 'Office Expense', valueA: '$4,267.89', valueB: '$4,267.89', match: true },
    ],
  },
  {
    EngagementId: 5001,
    EngagementPageId: 4,
    EngagementFormId: 1099,
    EngagementFieldGroupId: 30,
    FieldGroupId: 300,
    EngagementFaxFormId: 6003,
    FaxRowNumber: 3,
    TaxFormInstanceNo: 1,
    ConfidenceLevel: 0.68,
    MatchStatus: false,
    fieldLabel: '1099-MISC Other Income',
    sourceValue: '1099-MISC Box 3',
    returnValue: '1040 Schedule 1, Line 8z',
    documentRef: { pdfPath: PDF_PATH, pageNumber: 4, formType: '1099-MISC', formLabel: '1099-MISC (RICHMONT NORTH AMERICA)', imagePath: IMG['1099-misc'] },
    comparedValues: [
      { field: 'Recipient Name', valueA: 'JACK ANDERSON (1099-MISC)', valueB: 'JILL ANDERSON (1040 Filer)', match: false },
      { field: 'Recipient TIN', valueA: '111-11-1111', valueB: '***-**-1234', match: false },
      { field: 'Box 3 Amount', valueA: '$14,921.24', valueB: '$14,921.24', match: true },
      { field: 'Payer TIN', valueA: '13-2852910', valueB: '13-2852910', match: true },
    ],
  },
  {
    EngagementId: 5001,
    EngagementPageId: 5,
    EngagementFormId: 1041,
    EngagementFieldGroupId: 40,
    FieldGroupId: 400,
    EngagementFaxFormId: 6004,
    FaxRowNumber: 4,
    TaxFormInstanceNo: 1,
    ConfidenceLevel: 0.90,
    MatchStatus: true,
    fieldLabel: 'K-1 Interest & Dividends',
    sourceValue: 'K-1 (Form 1041) Boxes 1, 2a',
    returnValue: '1040 Schedule B',
    documentRef: { pdfPath: PDF_PATH, pageNumber: 5, formType: 'Schedule K-1', formLabel: 'K-1 (CHAPMAN IRREVOCABLE TRUST)', imagePath: IMG['k1'] },
    comparedValues: [
      { field: 'Trust Name', valueA: 'CHAPMAN IRREVOCABLE TRUST', valueB: 'CHAPMAN IRREVOCABLE TRUST', match: true },
      { field: 'Trust EIN', valueA: '34-3353535', valueB: '34-3353535', match: true },
      { field: 'Interest Income (Box 1)', valueA: '$2,575', valueB: '$2,575', match: true },
      { field: 'Ordinary Dividends (Box 2a)', valueA: '$62,565', valueB: '$62,565', match: true },
      { field: 'Qualified Dividends (Box 2b)', valueA: '$52,355', valueB: '$52,355', match: true },
    ],
  },
  {
    EngagementId: 5001,
    EngagementPageId: 5,
    EngagementFormId: 1041,
    EngagementFieldGroupId: 50,
    FieldGroupId: 500,
    EngagementFaxFormId: 6005,
    FaxRowNumber: 5,
    TaxFormInstanceNo: 1,
    ConfidenceLevel: 0.55,
    MatchStatus: false,
    fieldLabel: 'K-1 Business Income',
    sourceValue: 'K-1 (Form 1041) Box 6',
    returnValue: '1040 Schedule E, Part III',
    documentRef: { pdfPath: PDF_PATH, pageNumber: 5, formType: 'Schedule K-1', formLabel: 'K-1 (CHAPMAN IRREVOCABLE TRUST)', imagePath: IMG['k1'] },
    comparedValues: [
      { field: 'Business Income (Box 6)', valueA: '$8,748', valueB: '$9,200', match: false },
      { field: 'Beneficiary Name', valueA: 'JILL BAKER FAMILY TRUST', valueB: 'JILL ANDERSON', match: false },
      { field: 'Beneficiary ID', valueA: '12-3674289', valueB: '***-**-1234', match: false },
      { field: 'Estate Tax Deduction', valueA: '$680 (A) / $2,755 (B)', valueB: '$680', match: false },
    ],
  },
]
