import type { Binder, SupersededRecord, DuplicateRecord, CfaRecord, NfrRecord } from '@/lib/types'

const PDF_PATH = '/documents/1TDI-CCH-2024-binder.pdf'

export const binderA: Binder = {
  id: 'demo-a',
  label: 'Demo Binder A',
  taxpayerName: 'Jill Anderson',
  taxYear: 2024,
  totalDocuments: 4,
  summary: [
    { wizardType: 'superseded', totalItems: 6, highConfidence: 3, mediumConfidence: 2, lowConfidence: 1 },
    { wizardType: 'duplicate', totalItems: 6, highConfidence: 3, mediumConfidence: 2, lowConfidence: 1 },
    { wizardType: 'cfa', totalItems: 4, highConfidence: 3, mediumConfidence: 1, lowConfidence: 0 },
    { wizardType: 'nfr', totalItems: 5, highConfidence: 3, mediumConfidence: 1, lowConfidence: 1 },
  ],
}

export const supersededA: SupersededRecord[] = [
  {
    engagementPageId: 1,
    isSuperseded: true,
    retainedPageId: 4,
    confidenceLevel: 0.96,
    decisionType: 'Superseded',
    appliedRuleSet: 'SourceDocs',
    decisionRule: 'SUPERSEDED_BY_AMENDED',
    decisionReason: 'W-2 from WHYNOT STOP INC received on 01/15/2024 is superseded by a corrected W-2C received 03/01/2024. Employee SSN, employer EIN, and tax year all match.',
    reviewRequired: false,
    escalationReason: null,
    documentRef: { pdfPath: PDF_PATH, pageNumber: 1, formType: 'W-2', formLabel: 'W-2 (WHYNOT STOP INC)' },
    comparedValues: [
      { field: 'Employee Name', valueA: 'JILL ANDERSON', valueB: 'JILL ANDERSON', match: true },
      { field: 'Employee SSN', valueA: '***-**-1234', valueB: '***-**-1234', match: true },
      { field: 'Employer Name', valueA: 'WHYNOT STOP INC', valueB: 'WHYNOT STOP INC', match: true },
      { field: 'Employer EIN', valueA: '53-XXXXXXX', valueB: '53-XXXXXXX', match: true },
      { field: 'Tax Year', valueA: '2024', valueB: '2024', match: true },
      { field: 'Received Date', valueA: '01/15/2024', valueB: '03/01/2024', match: false },
    ],
  },
  {
    engagementPageId: 2,
    isSuperseded: false,
    retainedPageId: null,
    confidenceLevel: 0.93,
    decisionType: 'Original',
    appliedRuleSet: 'SourceDocs',
    decisionRule: 'ORIGINAL_RETAINED',
    decisionReason: 'Schedule C for Jill\'s Craft Shop is the only business income statement in the binder. No amended Schedule C found.',
    reviewRequired: false,
    escalationReason: null,
    documentRef: { pdfPath: PDF_PATH, pageNumber: 3, formType: 'Schedule C', formLabel: 'Schedule C (Jill\'s Craft Shop)' },
    comparedValues: [
      { field: 'Business Name', valueA: 'Jill\'s Craft Shop', valueB: '(no other filing)', match: true },
      { field: 'Net Income', valueA: '$28,119.85', valueB: '(no other filing)', match: true },
      { field: 'Received Date', valueA: '02/10/2024', valueB: '(no other filing)', match: true },
    ],
  },
  {
    engagementPageId: 3,
    isSuperseded: false,
    retainedPageId: null,
    confidenceLevel: 0.91,
    decisionType: 'Original',
    appliedRuleSet: 'SourceDocs',
    decisionRule: 'ORIGINAL_RETAINED',
    decisionReason: '1099-MISC from RICHMONT NORTH AMERICA INC is the only 1099-MISC for recipient JACK ANDERSON. No corrected version found.',
    reviewRequired: false,
    escalationReason: null,
    documentRef: { pdfPath: PDF_PATH, pageNumber: 4, formType: '1099-MISC', formLabel: '1099-MISC (RICHMONT NORTH AMERICA)' },
    comparedValues: [
      { field: 'Payer Name', valueA: 'RICHMONT NORTH AMERICA, INC', valueB: '(no other filing)', match: true },
      { field: 'Payer TIN', valueA: '13-2852910', valueB: '(no other filing)', match: true },
      { field: 'Recipient Name', valueA: 'JACK ANDERSON', valueB: '(no other filing)', match: true },
      { field: 'Recipient TIN', valueA: '111-11-1111', valueB: '(no other filing)', match: true },
      { field: 'Box 3 (Other Income)', valueA: '$14,921.24', valueB: '(no other filing)', match: true },
    ],
  },
  {
    engagementPageId: 4,
    isSuperseded: false,
    retainedPageId: null,
    confidenceLevel: 0.82,
    decisionType: 'RetainBoth',
    appliedRuleSet: 'SourceDocs',
    decisionRule: 'PARTIAL_OVERLAP',
    decisionReason: 'W-2 for JILL ANDERSON and 1099-MISC for JACK ANDERSON share the same address (1234 MAIN STREET, DALLAS, TX 75202) but are for different taxpayers with different TINs. Both forms are valid.',
    reviewRequired: true,
    escalationReason: null,
    documentRef: { pdfPath: PDF_PATH, pageNumber: 1, formType: 'W-2', formLabel: 'W-2 (WHYNOT STOP INC)' },
    comparedValues: [
      { field: 'Taxpayer Name', valueA: 'JILL ANDERSON', valueB: 'JACK ANDERSON', match: false },
      { field: 'TIN', valueA: '***-**-1234', valueB: '111-11-1111', match: false },
      { field: 'Address', valueA: '1234 MAIN STREET, DALLAS, TX 75202', valueB: '1234 MAIN STREET, DALLAS, TX 75202', match: true },
      { field: 'Form Type', valueA: 'W-2', valueB: '1099-MISC', match: false },
    ],
  },
  {
    engagementPageId: 5,
    isSuperseded: true,
    retainedPageId: 1,
    confidenceLevel: 0.74,
    decisionType: 'Superseded',
    appliedRuleSet: 'SourceDocs',
    decisionRule: 'SUPERSEDED_BY_AMENDED',
    decisionReason: 'K-1 (Form 1041) for JILL BAKER FAMILY TRUST may have been superseded by an amended K-1. Trust EIN matches but beneficiary ID differs slightly. Manual review recommended.',
    reviewRequired: true,
    escalationReason: null,
    documentRef: { pdfPath: PDF_PATH, pageNumber: 5, formType: 'Schedule K-1', formLabel: 'K-1 (CHAPMAN IRREVOCABLE TRUST)' },
    comparedValues: [
      { field: 'Trust Name', valueA: 'CHAPMAN IRREVOCABLE TRUST', valueB: 'CHAPMAN IRREVOCABLE TRUST', match: true },
      { field: 'Trust EIN', valueA: '34-3353535', valueB: '34-3353535', match: true },
      { field: 'Beneficiary Name', valueA: 'JILL BAKER FAMILY TRUST', valueB: 'JILL B. FAMILY TRUST', match: false },
      { field: 'Beneficiary ID', valueA: '12-3674289', valueB: '12-3674290', match: false },
      { field: 'Interest Income', valueA: '$2,575', valueB: '$2,575', match: true },
      { field: 'Ordinary Dividends', valueA: '$62,565', valueB: '$62,890', match: false },
    ],
  },
  {
    engagementPageId: 6,
    isSuperseded: true,
    retainedPageId: 2,
    confidenceLevel: 0.58,
    decisionType: 'Superseded',
    appliedRuleSet: 'ConsolidatedStatements',
    decisionRule: 'SUPERSEDED_UNCERTAIN',
    decisionReason: 'Two versions of Schedule C for Jill\'s Craft Shop found. Both show similar income ($48,650 vs $48,200) but expenses differ ($13,080.15 vs $14,500.00). Received dates are only 2 days apart.',
    reviewRequired: true,
    escalationReason: 'Confidence below threshold. Income amounts are close but not identical. Expense totals differ by $1,419.85. Could be corrected filing or data entry error.',
    documentRef: { pdfPath: PDF_PATH, pageNumber: 3, formType: 'Schedule C', formLabel: 'Schedule C (Jill\'s Craft Shop) v2' },
    comparedValues: [
      { field: 'Business Name', valueA: 'Jill\'s Craft Shop', valueB: 'Jill\'s Craft Shop', match: true },
      { field: 'Total Income', valueA: '$48,650.00', valueB: '$48,200.00', match: false },
      { field: 'Total Expenses', valueA: '$13,080.15', valueB: '$14,500.00', match: false },
      { field: 'Net Income', valueA: '$28,119.85', valueB: '$33,700.00', match: false },
      { field: 'Received Date', valueA: '02/10/2024', valueB: '02/12/2024', match: false },
    ],
  },
]

export const duplicateA: DuplicateRecord[] = [
  {
    itemType: 'DUPLICATE_DATA',
    organizerItemId: 'ORG-001',
    sourceReferenceId: 'SRC-001',
    decision: 'DuplicateData',
    matchType: 'DirectAmount',
    confidenceLevel: 0.97,
    appliedRuleSet: 'DUP-DATA',
    decisionRule: 'EXACT_DATA_MATCH',
    decisionReason: 'W-2 wages from WHYNOT STOP INC match exactly between source document and organizer entry. All key fields verified.',
    fieldsCompared: ['SSN', 'EIN', 'WagesAmount', 'FederalWithheld', 'TaxYear'],
    reviewRequired: false,
    escalationReason: null,
    comparedValues: [
      { field: 'Employee SSN', valueA: '***-**-1234', valueB: '***-**-1234', match: true },
      { field: 'Employer EIN', valueA: '53-XXXXXXX', valueB: '53-XXXXXXX', match: true },
      { field: 'Employer Name', valueA: 'WHYNOT STOP INC', valueB: 'WHYNOT STOP INC', match: true },
      { field: 'Employee Address', valueA: '1234 MAIN STREET, DALLAS, TX 75202', valueB: '1234 MAIN STREET, DALLAS, TX 75202', match: true },
      { field: 'Tax Year', valueA: '2024', valueB: '2024', match: true },
    ],
    documentRefA: { pdfPath: PDF_PATH, pageNumber: 1, formType: 'W-2', formLabel: 'W-2 (Source Doc)' },
    documentRefB: { pdfPath: PDF_PATH, pageNumber: 1, formType: 'W-2', formLabel: 'W-2 (Organizer)' },
  },
  {
    itemType: 'DUPLICATE_DATA',
    organizerItemId: 'ORG-002',
    sourceReferenceId: 'SRC-002',
    decision: 'DuplicateData',
    matchType: 'DirectAmount',
    confidenceLevel: 0.94,
    appliedRuleSet: 'DUP-DATA',
    decisionRule: 'NEAR_DATA_MATCH',
    decisionReason: '1099-MISC other income from RICHMONT NORTH AMERICA matches. Box 3 amount $14,921.24 is identical. Payer TIN confirmed.',
    fieldsCompared: ['RecipientTIN', 'PayerTIN', 'OtherIncome', 'TaxYear'],
    reviewRequired: false,
    escalationReason: null,
    comparedValues: [
      { field: 'Recipient Name', valueA: 'JACK ANDERSON', valueB: 'JACK ANDERSON', match: true },
      { field: 'Recipient TIN', valueA: '111-11-1111', valueB: '111-11-1111', match: true },
      { field: 'Payer Name', valueA: 'RICHMONT NORTH AMERICA, INC', valueB: 'RICHMONT NORTH AMERICA, INC', match: true },
      { field: 'Payer TIN', valueA: '13-2852910', valueB: '13-2852910', match: true },
      { field: 'Box 3 (Other Income)', valueA: '$14,921.24', valueB: '$14,921.24', match: true },
    ],
    documentRefA: { pdfPath: PDF_PATH, pageNumber: 4, formType: '1099-MISC', formLabel: '1099-MISC (Source)' },
    documentRefB: { pdfPath: PDF_PATH, pageNumber: 4, formType: '1099-MISC', formLabel: '1099-MISC (Organizer)' },
  },
  {
    itemType: 'DUPLICATE_DATA',
    organizerItemId: 'ORG-003',
    sourceReferenceId: 'SRC-003',
    decision: 'NotDuplicateData',
    matchType: 'Other',
    confidenceLevel: 0.99,
    appliedRuleSet: 'DUP-DATA',
    decisionRule: 'DIFFERENT_PAYER',
    decisionReason: 'W-2 (WHYNOT STOP INC) and 1099-MISC (RICHMONT NORTH AMERICA) are from different payers for different recipients. Not duplicates.',
    fieldsCompared: ['TaxpayerName', 'PayerEIN', 'PayerName', 'FormType'],
    reviewRequired: false,
    escalationReason: null,
    comparedValues: [
      { field: 'Form Type', valueA: 'W-2', valueB: '1099-MISC', match: false },
      { field: 'Recipient', valueA: 'JILL ANDERSON', valueB: 'JACK ANDERSON', match: false },
      { field: 'Payer', valueA: 'WHYNOT STOP INC', valueB: 'RICHMONT NORTH AMERICA, INC', match: false },
      { field: 'Payer TIN', valueA: '53-XXXXXXX', valueB: '13-2852910', match: false },
      { field: 'Address', valueA: '1234 MAIN STREET, DALLAS, TX 75202', valueB: '1234 MAIN STREET, DALLAS, TX 75202', match: true },
    ],
    documentRefA: { pdfPath: PDF_PATH, pageNumber: 1, formType: 'W-2', formLabel: 'W-2 (WHYNOT STOP)' },
    documentRefB: { pdfPath: PDF_PATH, pageNumber: 4, formType: '1099-MISC', formLabel: '1099-MISC (RICHMONT)' },
  },
  {
    itemType: 'DUPLICATE_SOURCE_DOC',
    docIdA: 101,
    docIdB: 105,
    decision: 'Duplicate',
    retainDocId: 101,
    confidenceLevel: 0.88,
    appliedRuleSet: 'DUP-SRC',
    decisionRule: 'VISUAL_DOC_MATCH',
    decisionReason: 'Two copies of W-2 from WHYNOT STOP INC for JILL ANDERSON found in binder. 92% pixel similarity. Likely same document scanned twice.',
    fieldsCompared: ['PixelHash', 'OCRText', 'PageDimensions', 'EmployerName'],
    reviewRequired: true,
    escalationReason: null,
    comparedValues: [
      { field: 'Employer Name', valueA: 'WHYNOT STOP INC', valueB: 'WHYNOT STOP INC', match: true },
      { field: 'Employee Name', valueA: 'JILL ANDERSON', valueB: 'JILL ANDERSON', match: true },
      { field: 'Pixel Similarity', valueA: '92%', valueB: '92%', match: true },
      { field: 'Page Dimensions', valueA: '8.5 x 11 in', valueB: '8.5 x 11 in', match: true },
      { field: 'Scan Quality', valueA: '300 DPI', valueB: '150 DPI', match: false },
    ],
    documentRefA: { pdfPath: PDF_PATH, pageNumber: 1, formType: 'W-2', formLabel: 'W-2 Scan A' },
    documentRefB: { pdfPath: PDF_PATH, pageNumber: 2, formType: 'W-2', formLabel: 'W-2 Scan B' },
  },
  {
    itemType: 'DUPLICATE_SOURCE_DOC',
    docIdA: 102,
    docIdB: 108,
    decision: 'Duplicate',
    retainDocId: 102,
    confidenceLevel: 0.72,
    appliedRuleSet: 'DUP-SRC',
    decisionRule: 'PARTIAL_DOC_MATCH',
    decisionReason: 'Schedule C pages share layout but total income differs ($48,650 vs $48,200). Could be corrected version of the same form.',
    fieldsCompared: ['PixelHash', 'OCRText', 'FormType', 'TotalIncome'],
    reviewRequired: true,
    escalationReason: null,
    comparedValues: [
      { field: 'Business Name', valueA: 'Jill\'s Craft Shop', valueB: 'Jill\'s Craft Shop', match: true },
      { field: 'Total Income', valueA: '$48,650.00', valueB: '$48,200.00', match: false },
      { field: 'Net Income', valueA: '$28,119.85', valueB: '$33,700.00', match: false },
      { field: 'Form Type', valueA: 'Schedule C', valueB: 'Schedule C', match: true },
    ],
    documentRefA: { pdfPath: PDF_PATH, pageNumber: 3, formType: 'Schedule C', formLabel: 'Sched C (v1)' },
    documentRefB: { pdfPath: PDF_PATH, pageNumber: 3, formType: 'Schedule C', formLabel: 'Sched C (v2)' },
  },
  {
    itemType: 'DUPLICATE_CONSOLIDATED_STATEMENT',
    docIdA: 200,
    docIdB: 205,
    decision: 'Duplicate',
    retainDocId: null,
    confidenceLevel: 0.61,
    appliedRuleSet: 'DUP-CS',
    decisionRule: 'UNCERTAIN_DOC_MATCH',
    decisionReason: 'K-1 statements from CHAPMAN IRREVOCABLE TRUST have matching EIN (34-3353535) but different dividend amounts ($62,565 vs $62,890). May represent different distribution periods.',
    fieldsCompared: ['TrustEIN', 'BeneficiaryID', 'InterestIncome', 'Dividends'],
    reviewRequired: true,
    escalationReason: 'Confidence below threshold. Dividend amounts differ by $325. Could be amended K-1 or different reporting period.',
    comparedValues: [
      { field: 'Trust Name', valueA: 'CHAPMAN IRREVOCABLE TRUST', valueB: 'CHAPMAN IRREVOCABLE TRUST', match: true },
      { field: 'Trust EIN', valueA: '34-3353535', valueB: '34-3353535', match: true },
      { field: 'Beneficiary', valueA: 'JILL BAKER FAMILY TRUST', valueB: 'JILL BAKER FAMILY TRUST', match: true },
      { field: 'Interest Income', valueA: '$2,575', valueB: '$2,575', match: true },
      { field: 'Ordinary Dividends', valueA: '$62,565', valueB: '$62,890', match: false },
      { field: 'Business Income', valueA: '$8,748', valueB: '$8,748', match: true },
    ],
    documentRefA: { pdfPath: PDF_PATH, pageNumber: 5, formType: 'K-1', formLabel: 'K-1 (v1)' },
    documentRefB: { pdfPath: PDF_PATH, pageNumber: 5, formType: 'K-1', formLabel: 'K-1 (v2)' },
  },
]

export const cfaA: CfaRecord[] = [
  {
    EngagementFaxFormId: 3001,
    ParentEngagementFaxFormId: 1001,
    EngagementPageId: 1,
    ConfidenceLevel: 0.95,
    IsAddForm: false,
    ParentFaxFormDwpCode: 'DWP-100',
    ParentFaxFormId: 1001,
    childFormLabel: 'W-2 (WHYNOT STOP INC)',
    parentFormLabel: 'Form 1040 (Jill Anderson)',
    documentRef: { pdfPath: PDF_PATH, pageNumber: 1, formType: 'W-2', formLabel: 'W-2 (WHYNOT STOP INC)' },
    comparedValues: [
      { field: 'Employee Name', valueA: 'JILL ANDERSON', valueB: 'JILL ANDERSON (1040 Filer)', match: true },
      { field: 'Employee SSN', valueA: '***-**-1234', valueB: '***-**-1234 (Primary SSN)', match: true },
      { field: 'Tax Year', valueA: '2024', valueB: '2024', match: true },
      { field: 'Employer Address', valueA: '532 MAIN STREET, WATERVILLE, ME 25570', valueB: 'N/A', match: true },
    ],
  },
  {
    EngagementFaxFormId: 3002,
    ParentEngagementFaxFormId: 1001,
    EngagementPageId: 3,
    ConfidenceLevel: 0.92,
    IsAddForm: false,
    ParentFaxFormDwpCode: 'DWP-200',
    ParentFaxFormId: 1001,
    childFormLabel: 'Schedule C (Jill\'s Craft Shop)',
    parentFormLabel: 'Form 1040 (Jill Anderson)',
    documentRef: { pdfPath: PDF_PATH, pageNumber: 3, formType: 'Schedule C', formLabel: 'Schedule C (Jill\'s Craft Shop)' },
    comparedValues: [
      { field: 'Proprietor Name', valueA: 'JILL ANDERSON', valueB: 'JILL ANDERSON (1040 Filer)', match: true },
      { field: 'Business Name', valueA: 'Jill\'s Craft Shop', valueB: 'N/A', match: true },
      { field: 'Net Income', valueA: '$28,119.85', valueB: '$28,119.85 (Line 12, Sched 1)', match: true },
      { field: 'Craft Sales', valueA: '$41,200.00', valueB: 'N/A', match: true },
      { field: 'Other Sales', valueA: '$7,450.00', valueB: 'N/A', match: true },
    ],
  },
  {
    EngagementFaxFormId: 3003,
    ParentEngagementFaxFormId: 1001,
    EngagementPageId: 4,
    ConfidenceLevel: 0.78,
    IsAddForm: true,
    ParentFaxFormDwpCode: 'DWP-300',
    ParentFaxFormId: 1001,
    childFormLabel: '1099-MISC (RICHMONT NORTH AMERICA)',
    parentFormLabel: 'Form 1040 (Jill Anderson)',
    documentRef: { pdfPath: PDF_PATH, pageNumber: 4, formType: '1099-MISC', formLabel: '1099-MISC (RICHMONT NORTH AMERICA)' },
    comparedValues: [
      { field: 'Recipient Name', valueA: 'JACK ANDERSON', valueB: 'JILL ANDERSON (1040 Filer)', match: false },
      { field: 'Recipient TIN', valueA: '111-11-1111', valueB: '***-**-1234 (Primary SSN)', match: false },
      { field: 'Address', valueA: '1234 MAIN STREET, DALLAS, TX 75202', valueB: '1234 MAIN STREET, DALLAS, TX 75202', match: true },
      { field: 'Box 3 (Other Income)', valueA: '$14,921.24', valueB: 'N/A', match: true },
    ],
  },
  {
    EngagementFaxFormId: 3004,
    ParentEngagementFaxFormId: 1001,
    EngagementPageId: 5,
    ConfidenceLevel: 0.91,
    IsAddForm: false,
    ParentFaxFormDwpCode: 'DWP-400',
    ParentFaxFormId: 1001,
    childFormLabel: 'K-1 Form 1041 (CHAPMAN IRREVOCABLE TRUST)',
    parentFormLabel: 'Form 1040 (Jill Anderson)',
    documentRef: { pdfPath: PDF_PATH, pageNumber: 5, formType: 'Schedule K-1', formLabel: 'K-1 (CHAPMAN IRREVOCABLE TRUST)' },
    comparedValues: [
      { field: 'Trust Name', valueA: 'CHAPMAN IRREVOCABLE TRUST', valueB: 'N/A', match: true },
      { field: 'Trust EIN', valueA: '34-3353535', valueB: 'N/A', match: true },
      { field: 'Beneficiary', valueA: 'JILL BAKER FAMILY TRUST', valueB: 'JILL ANDERSON (1040 Filer)', match: false },
      { field: 'Interest Income', valueA: '$2,575', valueB: '$2,575 (Sched B, Line 1)', match: true },
      { field: 'Ordinary Dividends', valueA: '$62,565', valueB: '$62,565 (Sched B, Line 5)', match: true },
      { field: 'Business Income', valueA: '$8,748', valueB: '$8,748 (Sched E, Part III)', match: true },
    ],
  },
]

export const nfrA: NfrRecord[] = [
  {
    EngagementId: 5001,
    EngagementPageId: 1,
    EngagementFormId: 1040,
    EngagementFieldGroupId: 10,
    FieldGroupId: 100,
    EngagementFaxFormId: 6001,
    FaxRowNumber: 1,
    TaxFormInstanceNo: 1,
    ConfidenceLevel: 0.96,
    MatchStatus: true,
    fieldLabel: 'W-2 Wages',
    sourceValue: 'W-2 Box 1 (WHYNOT STOP INC)',
    returnValue: '1040, Line 1a',
    documentRef: { pdfPath: PDF_PATH, pageNumber: 1, formType: 'W-2', formLabel: 'W-2 (WHYNOT STOP INC)' },
    comparedValues: [
      { field: 'Employer Name', valueA: 'WHYNOT STOP INC', valueB: 'WHYNOT STOP INC', match: true },
      { field: 'Employee Name', valueA: 'JILL ANDERSON', valueB: 'JILL ANDERSON', match: true },
      { field: 'Employee Address', valueA: '1234 MAIN STREET, DALLAS, TX 75202', valueB: '1234 MAIN STREET, DALLAS, TX 75202', match: true },
    ],
  },
  {
    EngagementId: 5001,
    EngagementPageId: 3,
    EngagementFormId: 1040,
    EngagementFieldGroupId: 20,
    FieldGroupId: 200,
    EngagementFaxFormId: 6002,
    FaxRowNumber: 2,
    TaxFormInstanceNo: 1,
    ConfidenceLevel: 0.93,
    MatchStatus: true,
    fieldLabel: 'Schedule C Net Income',
    sourceValue: 'Schedule C, Net Income',
    returnValue: '1040 Schedule 1, Line 3',
    documentRef: { pdfPath: PDF_PATH, pageNumber: 3, formType: 'Schedule C', formLabel: 'Schedule C (Jill\'s Craft Shop)' },
    comparedValues: [
      { field: 'Business Name', valueA: 'Jill\'s Craft Shop', valueB: 'Jill\'s Craft Shop', match: true },
      { field: 'Total Income', valueA: '$48,650.00', valueB: '$48,650.00', match: true },
      { field: 'Total Expenses', valueA: '$13,080.15', valueB: '$13,080.15', match: true },
      { field: 'Net Income', valueA: '$28,119.85', valueB: '$28,119.85', match: true },
      { field: 'Advertising', valueA: '$1,550.42', valueB: '$1,550.42', match: true },
      { field: 'Legal Fees', valueA: '$1,200.00', valueB: '$1,200.00', match: true },
      { field: 'Office Expense', valueA: '$4,267.89', valueB: '$4,267.89', match: true },
    ],
  },
  {
    EngagementId: 5001,
    EngagementPageId: 4,
    EngagementFormId: 1099,
    EngagementFieldGroupId: 30,
    FieldGroupId: 300,
    EngagementFaxFormId: 6003,
    FaxRowNumber: 3,
    TaxFormInstanceNo: 1,
    ConfidenceLevel: 0.68,
    MatchStatus: false,
    fieldLabel: '1099-MISC Other Income',
    sourceValue: '1099-MISC Box 3',
    returnValue: '1040 Schedule 1, Line 8z',
    documentRef: { pdfPath: PDF_PATH, pageNumber: 4, formType: '1099-MISC', formLabel: '1099-MISC (RICHMONT NORTH AMERICA)' },
    comparedValues: [
      { field: 'Recipient Name', valueA: 'JACK ANDERSON (1099-MISC)', valueB: 'JILL ANDERSON (1040 Filer)', match: false },
      { field: 'Recipient TIN', valueA: '111-11-1111', valueB: '***-**-1234', match: false },
      { field: 'Box 3 Amount', valueA: '$14,921.24', valueB: '$14,921.24', match: true },
      { field: 'Payer TIN', valueA: '13-2852910', valueB: '13-2852910', match: true },
    ],
  },
  {
    EngagementId: 5001,
    EngagementPageId: 5,
    EngagementFormId: 1041,
    EngagementFieldGroupId: 40,
    FieldGroupId: 400,
    EngagementFaxFormId: 6004,
    FaxRowNumber: 4,
    TaxFormInstanceNo: 1,
    ConfidenceLevel: 0.90,
    MatchStatus: true,
    fieldLabel: 'K-1 Interest & Dividends',
    sourceValue: 'K-1 (Form 1041) Boxes 1, 2a',
    returnValue: '1040 Schedule B',
    documentRef: { pdfPath: PDF_PATH, pageNumber: 5, formType: 'Schedule K-1', formLabel: 'K-1 (CHAPMAN IRREVOCABLE TRUST)' },
    comparedValues: [
      { field: 'Trust Name', valueA: 'CHAPMAN IRREVOCABLE TRUST', valueB: 'CHAPMAN IRREVOCABLE TRUST', match: true },
      { field: 'Trust EIN', valueA: '34-3353535', valueB: '34-3353535', match: true },
      { field: 'Interest Income (Box 1)', valueA: '$2,575', valueB: '$2,575', match: true },
      { field: 'Ordinary Dividends (Box 2a)', valueA: '$62,565', valueB: '$62,565', match: true },
      { field: 'Qualified Dividends (Box 2b)', valueA: '$52,355', valueB: '$52,355', match: true },
    ],
  },
  {
    EngagementId: 5001,
    EngagementPageId: 5,
    EngagementFormId: 1041,
    EngagementFieldGroupId: 50,
    FieldGroupId: 500,
    EngagementFaxFormId: 6005,
    FaxRowNumber: 5,
    TaxFormInstanceNo: 1,
    ConfidenceLevel: 0.55,
    MatchStatus: false,
    fieldLabel: 'K-1 Business Income',
    sourceValue: 'K-1 (Form 1041) Box 6',
    returnValue: '1040 Schedule E, Part III',
    documentRef: { pdfPath: PDF_PATH, pageNumber: 5, formType: 'Schedule K-1', formLabel: 'K-1 (CHAPMAN IRREVOCABLE TRUST)' },
    comparedValues: [
      { field: 'Business Income (Box 6)', valueA: '$8,748', valueB: '$9,200', match: false },
      { field: 'Beneficiary Name', valueA: 'JILL BAKER FAMILY TRUST', valueB: 'JILL ANDERSON', match: false },
      { field: 'Beneficiary ID', valueA: '12-3674289', valueB: '***-**-1234', match: false },
      { field: 'Estate Tax Deduction', valueA: '$680 (A) / $2,755 (B)', valueB: '$680', match: false },
    ],
  },
]
